{
    "name": "Dojang Migration",
    "summary": "SparkMembership → Odoo CSV migration tool (admin only)",
    "version": "19.0.1.0.0",
    "category": "Services",
    "license": "LGPL-3",
    "author": "Dojang",
    "depends": [
        "dojo_base",
        "dojo_members",
        "dojo_classes",
        "dojo_subscriptions",
        "dojo_belt_progression",
        "dojo_attendance",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/migration_log_views.xml",
        "views/import_programs_wizard.xml",
        "views/import_members_wizard.xml",
        "views/import_subscriptions_wizard.xml",
        "views/import_ranks_wizard.xml",
        "views/import_attendance_wizard.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
